version: '3.1'

services:

  mongodb:
    image: mongo
    volumes:
      - "./data/db:/data/db"
    secrets:
      - secret
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 30s
      retries: 10
    networks:
      - cards-network
    env_file:
      - ./cards-backend/mongo.env

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - cards-network

  backend:
    build:
      context: ./cards-backend
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cards-network
    volumes:
      - "./cards-backend:/app"
      - "/app/node_modules"
    env_file:
      - ./cards-backend/.env

#  python:
#    build:
#      context: ./cards-python
#    ports:
#        - "5000:5000"
#    networks:
#      - cards-network
#    volumes:
#      - "./cards-python:/app"


#  client:
#    build:
#      context: ./cards-web-platform
#    ports:
#      - "3000:3000"
#    networks:
#      - cards-network
#    volumes:
#      - "./cards-web-platform:/app"
#      - "/app/node_modules"

networks:
  cards-network:
    driver: bridge

secrets:
  secret:
    external: true