version: '3'

services:
  backend:
    build:
      context: ./cards-backend
    ports:
      - "8000:8000"
    networks:
      - cards-network
    volumes:
      - "./cards-backend:/app"
      - "/app/node_modules"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/cards
      - MONGO_DB_NAME=cards
      - JWT_SECRET=YYWz1EBc78%mqUX2xSUh%pv56#F6M3K3$7&6uk3v
      - NODE_ENV=development

  client:
    build:
      context: ./cards-web-platform
    ports:
      - "3000:3000"
    networks:
      - cards-network
    volumes:
      - "./cards-web-platform:/app"
      - "/app/node_modules"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"
    networks:
      - cards-network

networks:
  cards-network:
    driver: bridge
